### ISSUE TITLE
The Conversion error

### ISSUE THREAD

**Issue by linkliu** [UniFreak/jekyll-theme-textalic#1]
Jekyll::Converters::Scss encountered an error while converting 'assets/css/base.scss':
                    Error: It's not clear which file to import for '@import "font/font-awesome"'. Candidates: font/font-awesome.scss font/font-awesome.css Please delete or rename all but one of these files. on line 6:1 of base.scss >> @import "font/font-awesome"; ^

这个问题是一个CSS引用的时候，有歧义。
在_sass文件夹下，有个front的文件夹，下面有两个文件“font-awesome.css”和“font-awesome.scss”，由于在bass.scss这里引用的时候，没有给他们后缀名，导致jekyll不清楚该使用哪一个，
@import "font/font-awesome.scss";这样写可以解决

**Comment by UniFreak** [comment]
我试了一下并没有复现你说的问题. 但还是把你说的那个重复的文件 `font-awesome.css` 给去掉了.
麻烦在你的机子上看一下运行有问题没有. 感谢你的反馈 👍
